version: '2'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=America/Bogota
      - WEBHOOK_URL=https://n8n.julidcardenas.site/
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - redinterna                    # Usa red docker externa

networks:
  redinterna:
    external: true
